spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: smartcity
    password: smartcity
    url: jdbc:mysql://192.168.30.250:3307/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
  session:
    store-type: none
#  security:
#    user:
#      name: admin
#      password: 123456
server:
  port: 80


#wcn:
#  security:
#    browser:
#      loginPage: /demo-signIn.html
#      loginType: REDIRECT
