spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wcnwcn175
    url: jdbc:mysql://cl0505.club:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&useSSL=false
  session:
    store-type: none
#  security:
#    user:
#      name: admin
#      password: 123456
server:
  port: 80


wcn:
  security:
    social:
      qq:
        app-id:
        app-secret:
#    code:
#      image:
#        length: 6
#        width: 100
#        url: /user,/user/*
#    browser:
#      loginPage: /demo-signIn.html
#      loginType: REDIRECT
