spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wcnwcn175
#    url: jdbc:mysql://cl0505.club:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    url: jdbc:mysql://106.37.127.192:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  session:
    store-type: none
  rabbitmq:
    host: 192.168.30.16
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0
#  security:
#    user:
#      name: admin
#      password: 123456
server:
  port: 80
  servlet:
    session:
      timeout: 36000



wcn:
  security:
    social:
      qq:
        app-id: 101766980
        app-secret: 6e3ccf997f3a924de88804e86401ed0b
#        app-id: 101760025
#        app-secret: 6739fd15d80a02f2427045742194451f
        providerId: callback.do
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
      filterProcessUrl: /qqLogin
#    code:
#      image:
#        length: 6
#        width: 100
#        url: /user,/user/*
    browser:
      signUpUrl: /demo-signUp.html
#      loginPage: /demo-signIn.html
#      loginType: REDIRECT
